stages:
  - build

before_script:
  - export src_dir=${CI_PROJECT_DIR}
  - export git_hash=${CI_COMMIT_SHA:0:6}
  - export pb_dir="${src_dir}/scikit-surgeryopencvcpp-build"
  - hostname
  - whoami
  - pwd
  - echo "Sources - ${src_dir}"
  - echo "Commit - ${git_hash}"
  - echo "Project build - ${pb_dir}"
  - cmake --version
  - python --version

##########################################
# Continuous build jobs
##########################################

Linux continuous build:

  stage: build

  script:
    - mkdir -p ${pb_dir}
    - cd ${pb_dir}
    - cmake -DSKSURGERYOPENCVCPP_PYTHON_VERSION:STRING=3.6
            -DBUILD_SUPERBUILD:BOOL=ON
            -DBUILD_TESTING:BOOL=ON
            ${src_dir}
    - make -j 1

  only:
    - branches

  tags:
    - python, shared-linux, ubuntu-18.04